name: Publish to Medium
on:
  push:
    branches:
      - main
    paths:
      - "content/post/**.md"
      - "!content/post/_index.md"

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11.2
      - name: Install requirements
        run: pip install -r scripts/requirements.txt
      - name: Run python publishing script
        run: |
          python scripts/publish-to-medium.py
