name: Publish Articles
run-name: ${{ github.actor }} is publishing to dev.to and medium.com!
on:
  push:
    branches: [main]
    paths:
      - "content/post/**.md"
      - "!content/post/_index.md"
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - id: files
        uses: jitterbit/get-changed-files@v1

      - id: posts
        name: Detecting posts from changed files
        run: |
          i=0
          for changed_file in ${{ steps.files.outputs.added_modified }}; do
            echo "Do something with ${changed_file}."
            if [[ ("${changed_file}" == "content/posts"*) && ("${changed_file}" != "content/posts/_index.md") ]];
            then
              echo "File ${changed_file} matched post."
              echo "::set-output name=post${i}::${changed_file}"
              ((i=i+1))
            fi
          done
      - if: steps.posts.outputs.post0
        name: Publish articles to dev.to
        uses: ful1e5/TheActionDev@v3
        with:
          api-key: ${{ secrets.DEVTO_API_KEY }}
          directory: ./content/post
          ignore: _index.md
      - if: steps.posts.outputs.post0
        name: Publish articles to medium.com
        uses: infraway/medium-post-markdown@v1.6.0
        with:
          access_token: ${{ secrets.MEDIUM_API_KEY }}
          markdown_file: ${{ steps.posts.outputs.post0 }}
          base_url: "https://devbranch.co"
